### ISSUE TITLE
Unexpected Crash in parser.py (line 63)

### ISSUE THREAD

**Issue by mateuszk87** [ethereum/vyper#1184]
### Version Information

* vyper Version: 0.1.0b6
* OS: osx
* Python Version (python --version): Python 3.6.3

### What's your issue about?

It is possible to cause an unexpected crash. This can lead to security bugs in dependent systems (e.g. in future [VerifiedContracts](https://etherscan.io/verifyContract2). Actually, [this is why fuzzing solc is so interesting for us, too](https://github.com/Ethermat/solc-fuzzing)

Parser.py excerpt:
```
# Converts code to parse tree
def parse(code):
    class_names, code = pre_parse(code)
    o = ast.parse(code)  # <-- code can contain NULL bytes
    decorate_ast(o, code, class_names)  # decorated python ast 
    o = resolve_negative_literals(o)
    return o.body
```

### Reproduce Bug

 1. Vyper contract leading to the issue: [3.txt](https://github.com/ethereum/vyper/files/2758478/3.txt)

 2. Command to run: `vyper 3.txt`

 3. Output:

```
Traceback (most recent call last):
  File "/Users/mate/github/vyper/vyper-venv/bin/vyper", line 4, in <module>
    __import__('pkg_resources').run_script('vyper==0.1.0b6', 'vyper')
  File "/Users/mate/github/vyper/vyper-venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 664, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/mate/github/vyper/vyper-venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1451, in run_script
    exec(script_code, namespace, namespace)
  File "/Users/mate/github/vyper/vyper-venv/lib/python3.6/site-packages/vyper-0.1.0b6-py3.6.egg/EGG-INFO/scripts/vyper", line 85, in <module>
  File "/Users/mate/github/vyper/vyper-venv/lib/python3.6/site-packages/vyper-0.1.0b6-py3.6.egg/vyper/compiler.py", line 108, in compile_codes
  File "/Users/mate/github/vyper/vyper-venv/lib/python3.6/site-packages/vyper-0.1.0b6-py3.6.egg/EGG-INFO/scripts/vyper", line 51, in exc_handler
  File "/Users/mate/github/vyper/vyper-venv/lib/python3.6/site-packages/vyper-0.1.0b6-py3.6.egg/vyper/compiler.py", line 105, in compile_codes
  File "/Users/mate/github/vyper/vyper-venv/lib/python3.6/site-packages/vyper-0.1.0b6-py3.6.egg/vyper/compiler.py", line 87, in <lambda>
  File "/Users/mate/github/vyper/vyper-venv/lib/python3.6/site-packages/vyper-0.1.0b6-py3.6.egg/vyper/compiler.py", line 8, in __compile
  File "/Users/mate/github/vyper/vyper-venv/lib/python3.6/site-packages/vyper-0.1.0b6-py3.6.egg/vyper/parser/parser.py", line 63, in parse
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
ValueError: source code string cannot contain null bytes
```

**Comment by jacqueswww** [comment]
@mateuszk87 Interesting... so I am wondering how would this attack get escalated? I feel like causing an unexpected crash is only so useful.

**Comment by mateuszk87** [comment]
Implications of such errors are really broad. 

 1. First of all, it is possible to provoke error messages to get more information about the underlying system (information disclosure vulnerabilities). In some cases, these issues could contain sensitive information. 

 2. Potential Denial of Service attacks - that's pretty obvious though. Not in the sense of VerifiedContracts, but also other applications. Many projects make use of e.g. solc in different types of applications - check out how [github code search](https://github.com/search?q=solc&type=Code) or programatic dependency [Python only](https://github.com/search?q=py-solc&type=Code).

**Comment by jacqueswww** [comment]
I see, yes we will definitely fix the submitted tickets. Could you share the fuzzer setup you use, perhaps we could run it on every release we tag?

**Comment by mateuszk87** [comment]
Sure, I will disclose the wrapper code soon. Maybe adding the project to oss-fuzz would also make sense? I will check if it is applicable

**Comment by jacqueswww** [comment]
That would be awesome thanks :)

**Comment by jacqueswww** [comment]
Fixed in fuzzer branch.
