### ISSUE TITLE
Unexpected Crash in parser.py (line 234)

### ISSUE THREAD

**Issue by mateuszk87** [ethereum/vyper#1185]
### Version Information

* vyper Version: 0.1.0b6
* OS: osx
* Python Version (python --version): Python 3.6.3

### What's your issue about?

It is possible to cause an unexpected crash. This can lead to security bugs in dependent systems (e.g. in future [VerifiedContracts](https://etherscan.io/verifyContract2). Actually, [this is why fuzzing solc is so interesting for us, too](https://github.com/Ethermat/solc-fuzzing)

Parser.py excerpt:
```
# Main python parse tree => LLL method
def parse_tree_to_lll(code, origcode, runtime_only=False):
    global_ctx = GlobalContext.get_global_context(code)
    _names_def = [_def.name for _def in global_ctx._defs]
    # Checks for duplicate function names
    if len(set(_names_def)) < len(_names_def):
        raise FunctionDeclarationException("Duplicate function name: %s" % [name for name in _names_def if _names_def.count(name) > 1][0])
    _names_events = [_event.target.id for _event in global_ctx._events]  # <---- _event.target can have no id
```

### Reproduce Bug

 1. Vyper contract leading to the issue: [4.txt](https://github.com/ethereum/vyper/files/2758524/4.txt)
 
2. Command to run: `vyper 4.txt`

 3. Output:
```
Error compiling:  4.txt
Traceback (most recent call last):
  File "/Users/mate/ethermat/security/vyper-fuzz/venv/bin/vyper", line 4, in <module>
    __import__('pkg_resources').run_script('vyper==0.1.0b6', 'vyper')
  File "/Users/mate/ethermat/security/vyper-fuzz/venv/lib/python3.6/site-packages/setuptools-39.1.0-py3.6.egg/pkg_resources/__init__.py", line 658, in run_script
  File "/Users/mate/ethermat/security/vyper-fuzz/venv/lib/python3.6/site-packages/setuptools-39.1.0-py3.6.egg/pkg_resources/__init__.py", line 1445, in run_script
  File "/Users/mate/ethermat/security/vyper-fuzz/venv/lib/python3.6/site-packages/vyper-0.1.0b6-py3.6.egg/EGG-INFO/scripts/vyper", line 85, in <module>
  File "/Users/mate/ethermat/security/vyper-fuzz/venv/lib/python3.6/site-packages/vyper-0.1.0b6-py3.6.egg/vyper/compiler.py", line 108, in compile_codes
  File "/Users/mate/ethermat/security/vyper-fuzz/venv/lib/python3.6/site-packages/vyper-0.1.0b6-py3.6.egg/EGG-INFO/scripts/vyper", line 51, in exc_handler
  File "/Users/mate/ethermat/security/vyper-fuzz/venv/lib/python3.6/site-packages/vyper-0.1.0b6-py3.6.egg/vyper/compiler.py", line 105, in compile_codes
  File "/Users/mate/ethermat/security/vyper-fuzz/venv/lib/python3.6/site-packages/vyper-0.1.0b6-py3.6.egg/vyper/compiler.py", line 87, in <lambda>
  File "/Users/mate/ethermat/security/vyper-fuzz/venv/lib/python3.6/site-packages/vyper-0.1.0b6-py3.6.egg/vyper/compiler.py", line 8, in __compile
  File "/Users/mate/ethermat/security/vyper-fuzz/venv/lib/python3.6/site-packages/vyper-0.1.0b6-py3.6.egg/vyper/parser/parser.py", line 234, in parse_tree_to_lll
  File "/Users/mate/ethermat/security/vyper-fuzz/venv/lib/python3.6/site-packages/vyper-0.1.0b6-py3.6.egg/vyper/parser/parser.py", line 234, in <listcomp>
AttributeError: 'Attribute' object has no attribute 'id'
```

**Comment by jacqueswww** [comment]
Fixed in fuzzer mega branch.
