### ISSUE TITLE
Unexpected Crash in event_signature.py (line 54)

### ISSUE THREAD

**Issue by mateuszk87** [ethereum/vyper#1189]
### Version Information

* vyper Version: 0.1.0b6
* OS: osx
* Python Version (python --version): Python 3.6.3

### What's your issue about?

It is possible to cause an unexpected crash. This can lead to security bugs in dependent systems (e.g. in future [VerifiedContracts](https://etherscan.io/verifyContract2). Actually, [this is why fuzzing solc is so interesting for us, too](https://github.com/Ethermat/solc-fuzzing)

### Reproduce Bug

 1. Vyper contract leading to the issue: [6.txt](https://github.com/ethereum/vyper/files/2760913/6.txt)

 2. Command to run: `vyper 6.txt`

 3. Output:

```
Error compiling:  6.txt
Traceback (most recent call last):
  File "/Users/mate/github/vyper/vyper-venv/bin/vyper", line 4, in <module>
    __import__('pkg_resources').run_script('vyper==0.1.0b6', 'vyper')
  File "/Users/mate/github/vyper/vyper-venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 664, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/mate/github/vyper/vyper-venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1451, in run_script
    exec(script_code, namespace, namespace)
  File "/Users/mate/github/vyper/vyper-venv/lib/python3.6/site-packages/vyper-0.1.0b6-py3.6.egg/EGG-INFO/scripts/vyper", line 85, in <module>
  File "/Users/mate/github/vyper/vyper-venv/lib/python3.6/site-packages/vyper-0.1.0b6-py3.6.egg/vyper/compiler.py", line 108, in compile_codes
  File "/Users/mate/github/vyper/vyper-venv/lib/python3.6/site-packages/vyper-0.1.0b6-py3.6.egg/EGG-INFO/scripts/vyper", line 51, in exc_handler
  File "/Users/mate/github/vyper/vyper-venv/lib/python3.6/site-packages/vyper-0.1.0b6-py3.6.egg/vyper/compiler.py", line 105, in compile_codes
  File "/Users/mate/github/vyper/vyper-venv/lib/python3.6/site-packages/vyper-0.1.0b6-py3.6.egg/vyper/compiler.py", line 87, in <lambda>
  File "/Users/mate/github/vyper/vyper-venv/lib/python3.6/site-packages/vyper-0.1.0b6-py3.6.egg/vyper/compiler.py", line 8, in __compile
  File "/Users/mate/github/vyper/vyper-venv/lib/python3.6/site-packages/vyper-0.1.0b6-py3.6.egg/vyper/parser/parser.py", line 249, in parse_tree_to_lll
  File "/Users/mate/github/vyper/vyper-venv/lib/python3.6/site-packages/vyper-0.1.0b6-py3.6.egg/vyper/parser/parser.py", line 174, in parse_events
  File "/Users/mate/github/vyper/vyper-venv/lib/python3.6/site-packages/vyper-0.1.0b6-py3.6.egg/vyper/signatures/event_signature.py", line 54, in from_declaration
AttributeError: 'BinOp' object has no attribute 'id'


```

**Comment by jacqueswww** [comment]
Fixed in fuzzer mega branch.
