### ISSUE TITLE
Can't deploy RLP decoder

### ISSUE THREAD

**Issue by ackintosh** [ethereum/vyper#1435]
### Version Information

* vyper Version (output of `vyper --version`): 0.1.0b9
* OS: osx
* Python Version (output of `python --version`): Python 3.7.3
* Environment (output of `pip freeze`): pycryptodome==3.8.1, vyper==0.1.0b9

### What's your issue about?

I'm trying to deploy RLP decoder  according to [this document](https://github.com/ethereum/vyper/blob/master/docs/built-in-functions.rst#rlplist).  But it failed and show the message "invalid opcode". 😢 

### Truffle version

```sh
$ truffle version

Truffle v5.0.17 (core: 5.0.16)
Solidity v0.5.0 (solc-js)
Node v8.11.3
Web3.js v1.0.0-beta.37
```

### deployRLPdecoder.js

```js
const Tx = require("ethereumjs-tx");

const deployRLPdecoder = (account) => {
    const deployTx = "0xf90237808506fc23ac00830330888080b902246102128061000e60003961022056600060007f010000000000000000000000000000000000000000000000000000000000000060003504600060c082121515585760f882121561004d5760bf820336141558576001905061006e565b600181013560f783036020035260005160f6830301361415585760f6820390505b5b368112156101c2577f010000000000000000000000000000000000000000000000000000000000000081350483602086026040015260018501945060808112156100d55760018461044001526001828561046001376001820191506021840193506101bc565b60b881121561014357608081038461044001526080810360018301856104600137608181141561012e5760807f010000000000000000000000000000000000000000000000000000000000000060018401350412151558575b607f81038201915060608103840193506101bb565b60c08112156101b857600182013560b782036020035260005160388112157f010000000000000000000000000000000000000000000000000000000000000060018501350402155857808561044001528060b6838501038661046001378060b6830301830192506020810185019450506101ba565bfe5b5b5b5061006f565b601f841315155857602060208502016020810391505b6000821215156101fc578082604001510182826104400301526020820391506101d8565b808401610420528381018161044003f350505050505b6000f31b2d4f";

    web3.eth.sendTransaction({ from: account, to: "0xd2c560282c9C02465C2dAcdEF3E859E730848761", value: 6270960000000000 })

    web3.eth.getTransactionCount(account).then(txCount => {
        const txData = {
            nonce: web3.utils.toHex(txCount + 1),
            gas: 9999999999999,
            from: account,
            data: deployTx
        }
        const transaction = new Tx(txData);

        const privateKey = new Buffer('.............', 'hex')
        transaction.sign(privateKey);

        const serializedTx = transaction.serialize().toString('hex')
        web3.eth.sendSignedTransaction('0x' + serializedTx)
        .on('receipt', (receipt) => {
            console.log('receipt')
            console.log(receipt)
        })
        .on('error', (error) => {
            console.log('error')
            console.log(error)
        })
    });
}

module.exports = async (callback) => {
    const accounts = await web3.eth.getAccounts();
    deployRLPdecoder(accounts[0]);
}

```

### Error message

```sh
$ truffle exec helper/deployRLPdecoder.js  --network development


Using network 'development'.

error
Error: Returned error: VM Exception while processing transaction: invalid opcode
    at Object.ErrorResponse (/Users/akihito1/.nodebrew/node/v8.11.3/lib/node_modules/truffle/build/webpack:/~/web3-eth/~/web3-core-helpers/src/errors.js:29:1)
    at /Users/akihito1/.nodebrew/node/v8.11.3/lib/node_modules/truffle/build/webpack:/~/web3-eth/~/web3-core-requestmanager/src/index.js:140:1
    at /Users/akihito1/.nodebrew/node/v8.11.3/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:112:1
    at XMLHttpRequest.request.onreadystatechange (/Users/akihito1/.nodebrew/node/v8.11.3/lib/node_modules/truffle/build/webpack:/~/web3/~/web3-providers-http/src/index.js:96:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/akihito1/.nodebrew/node/v8.11.3/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
    at XMLHttpRequest._setReadyState (/Users/akihito1/.nodebrew/node/v8.11.3/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:208:1)
    at XMLHttpRequest._onHttpResponseEnd (/Users/akihito1/.nodebrew/node/v8.11.3/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:318:1)
    at IncomingMessage.<anonymous> (/Users/akihito1/.nodebrew/node/v8.11.3/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:289:47)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by ackintosh** [comment]
Using [this](https://github.com/cryptoeconomicslab/plasma-predicates/blob/master/test/helpers/deployRLPdecoder.js),  I've successfully deployed the RLPdecoder. 🎉 

@syuhei176 Thanks for your help. ✨

**Comment by ackintosh** [comment]
Closing this, as It was my bad.
