### ISSUE TITLE
as_num256 failed to reject negative arguments

### ISSUE THREAD

**Issue by daejunpark** [ethereum/vyper#469]
* viper Version: 0.0.2
* pyethereum Version: 2.1.0
* OS: linux
* Python Version (python --version): 3.6

### What's your issue about?

AFAIU, `as_num256(x)` should not be allowed when `x < 0`. If so, the compiler should reject at compile-time as much as possible, or insert runtime check to throw a runtime exception. However, the current compiler does not generate the runtime check even if it cannot prove `x >= 0`.

For example, `foo()` returns `2**256 - 1`:
```
def foo() -> num256:
    return as_num256(0 - 1)
```
while this:
```
def foo() -> num256:
    return as_num256(-1)
```
failed to be parsed:
```
viper.exceptions.InvalidLiteralException: line 2: Number out of range: -1
    return as_num256(-1)
----------------------^
```

Similarly, `bar(-1)` returns `2**256 - 1`:
```
def bar(x: num) -> num256:
    return as_num256(x)
```

### How can it be fixed?

For each `as_num256(x)`, generate runtime-check `assert(x >= 0)` when `x >= 0` cannot be proved at compile-time.

#### Cute Animal Picture

```
                              ___     _,.--.,_
                           .-~   ~--"~-.   ._ "-.
                          /      ./_    Y    "-. \
                         Y       :~     !         Y
                         lq p    |     /         .|
                      _   \. .-, l    /          |j
                     ()\___) |/   \_/";          !
                      \._____.-~\  .  ~\.      ./
                                 Y_ Y_. "vr"~  T
                                 (  (    |L    j   -Row
                                 [nn[nn..][nn..]
                             ~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by fubuloubu** [comment]
Totally on board with this. Does a runtime error get generated when `x: num256 - y: num256 > x`?

**Comment by daejunpark** [comment]
@fubuloubu Yep,
```
from ethereum.tools import tester as t
from ethereum.slogging import configure_logging

#configure_logging(':trace')
s = t.Chain()
from viper import compiler

code = """
def foo(x: num256, y: num256) -> num256:
    return num256_sub(x, y)
"""

t.languages['viper'] = compiler.Compiler()

c = s.contract(code, language='viper')

print(c.foo(1,2)) # TransactionFailed
```

error:
```
Traceback (most recent call last):
  File "run.py", line 17, in <module>
    print(c.foo(1,2))
  File "/home/daejunpark/x/venv/lib/python3.6/site-packages/ethereum-2.1.0-py3.6.egg/ethereum/tools/tester.py", line 103, in kall
    gasprice=kwargs.get('gasprice', GASPRICE)
  File "/home/daejunpark/x/venv/lib/python3.6/site-packages/ethereum-2.1.0-py3.6.egg/ethereum/tools/tester.py", line 194, in tx
    output = self.direct_tx(transaction)
  File "/home/daejunpark/x/venv/lib/python3.6/site-packages/ethereum-2.1.0-py3.6.egg/ethereum/tools/tester.py", line 185, in direct_tx
    raise TransactionFailed()
ethereum.tools.tester.TransactionFailed
```

**Comment by fubuloubu** [comment]
Fantastic! Is there a test like that? Haha

**Comment by fubuloubu** [comment]
E.g. `2-1 == 1`, `2-2 == 0`, and `2-3 throws`?

But like use really big numbers for 1, 2, and 3

**Comment by Dishendramishra** [comment]
in which file num256_sub() is defined?

**Comment by DavidKnott** [comment]
@Dishendramishra All `num256` functionality is defined in `functions.py`

**Comment by DavidKnott** [comment]
@daejunpark Thanks for making an issue, this has been fixed.  Closing.
