### ISSUE TITLE
Failed to compile on_chain_market_maker.v.py

### ISSUE THREAD

**Issue by stupidkitten** [ethereum/vyper#528]
Unable to compile on_chain_market_maker.v.py due to an error:
 `Traceback (most recent call last):
  File "/usr/local/bin/viper", line 4, in <module>
    __import__('pkg_resources').run_script('viper==0.0.2', 'viper')
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1524, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/site-packages/viper-0.0.2-py3.6.egg/EGG-INFO/scripts/viper", line 31, in <module>
  File "/usr/local/lib/python3.6/site-packages/viper-0.0.2-py3.6.egg/viper/compiler.py", line 11, in compile
  File "/usr/local/lib/python3.6/site-packages/viper-0.0.2-py3.6.egg/viper/parser/parser.py", line 346, in parse_tree_to_lll
  File "/usr/local/lib/python3.6/site-packages/viper-0.0.2-py3.6.egg/viper/parser/parser.py", line 222, in get_contracts_and_defs_and_globals
  File "/usr/local/lib/python3.6/site-packages/viper-0.0.2-py3.6.egg/viper/parser/parser.py", line 202, in add_globals_and_events
  File "/usr/local/lib/python3.6/site-packages/viper-0.0.2-py3.6.egg/viper/types.py", line 256, in parse_type
    # implements collections.abc.Generator (and does not implement
viper.exceptions.InvalidTypeException: line 4: Base type with units can only be num and decimal
token_address: address(ERC20)
---------------^
`

What `ERC20` means in this context? Should I deploy ERC20 contract first? 

* viper Version: 0.0.2

**Comment by fubuloubu** [comment]
ERC20 is a "built-in" interface contract in the parser, but I have no idea how this works in practice. Seemed a little weird to me.

**Comment by stupidkitten** [comment]
I was hopping that this example will allow me to understand how to call one contract from another (call and delegatecall).
Maybe there is another example that I missed?

**Comment by fubuloubu** [comment]
There are definitely easier examples of that in our tests

Check out [`tests/parser/features/external_contracts/`](https://github.com/ethereum/viper/tree/master/tests/parser/features/external_contracts)

**Comment by stupidkitten** [comment]
@fubuloubu thanks for the example!

But anyway the question about `on_chain_market_maker.v.py` build is still present.

**Comment by DavidKnott** [comment]
@stupidkitten Can you check if `on_chain_market_maker.v.py` is still failing to compile (it's currently working for me locally)?

**Comment by jacqueswww** [comment]
@stupidkitten  I just installed latest master and did a `make setup` in a fresh virtualenv, and definitely compiles there ;) Please give it a shot.

**Comment by jacqueswww** [comment]
Closing as there as not been any response on the issue in over a month.
