### ISSUE TITLE
Crowdfund example doesn't compile

### ISSUE THREAD

**Issue by casret** [ethereum/vyper#644]
* viper Version: 0.0.3
* pyethereum Version: 2.1.3
* OS: osx/linux/win
* Python Version (python --version): Python 3.6.4
* Environment (output of `pip freeze`):

ansicolors==1.1.8
ansiwrap==0.8.3
appnope==0.1.0
asn1crypto==0.24.0
attrs==17.4.0
bumpversion==0.5.3
cffi==1.11.4
chainmap==1.0.2
coincurve==6.0.0
combomethod==1.0.10
coverage==4.4.2
decorator==4.2.1
ethereum==2.1.3
future==0.16.0
ipython==6.2.1
ipython-genutils==0.2.0
jedi==0.11.1
mementos==1.2.8
nulltype==2.2.11
options==1.4.8
parso==0.1.1
pbkdf2==1.3
pexpect==4.3.1
pickleshare==0.7.4
pluggy==0.6.0
prompt-toolkit==1.0.15
ptyprocess==0.5.2
py==1.5.2
py-ecc==1.4.2
pycparser==2.18
pycryptodome==3.4.6
pyethash==0.1.27
Pygments==2.2.0
pysha3==1.0.2
pytest==3.3.2
pytest-cov==2.5.1
pytest-runner==3.0
PyYAML==3.12
readline==6.2.4.1
repoze.lru==0.7
rlp==0.6.0
say==1.6.5
scrypt==0.8.0
show==1.6.0
simplegeneric==0.8.1
simplere==1.2.13
six==1.11.0
textdata==1.7.3
textwrap3==0.9.1
traitlets==4.3.2
viper==0.0.3
wcwidth==0.1.7

### What's your issue about?
Following the install tutorial, and the example won't compile:

'''
Traceback (most recent call last):
  File "bin/viper", line 31, in <module>
    print('0x' + compiler.compile(code).hex())
  File "/Users/casret/.pyenv/versions/3.6.4/envs/viper/lib/python3.6/site-packages/viper-0.0.3-py3.6.egg/viper/compiler.py", line 11, in compile
  File "/Users/casret/.pyenv/versions/3.6.4/envs/viper/lib/python3.6/site-packages/viper-0.0.3-py3.6.egg/viper/parser/parser.py", line 64, in parse
  File "/Users/casret/.pyenv/versions/3.6.4/lib/python3.6/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 3
    funders: {sender: address, value: wei_value}[num]
          ^
SyntaxError: invalid syntax
'''

### How can it be fixed?

If I take out the @private annotation, it will compile.

#### Cute Animal Picture

> put a cute animal picture here.

**Comment by DavidKnott** [comment]
@casret Thanks for creating this issue!
