### ISSUE TITLE
Fix snapcraft

### ISSUE THREAD

**Issue by jacqueswww** [ethereum/vyper#871]
### What's your issue about?
There seems to be a problem with conflicting `python3`  file in snapcraft. Figure it out and make the snap work again.

```
$ vyper
Traceback (most recent call last):
  File "/snap/vyper/35/bin/vyper", line 5, in <module>
    import vyper
  File "/snap/vyper/35/lib/python3.5/site-packages/vyper/__init__.py", line 7, in <module>
    raise Exception("Requires python3.6+")  # pragma: no cover
Exception: Requires python3.6+

```
### How can it be fixed?

~

#### Cute Animal Picture
^.^

**Comment by jacqueswww** [comment]
Resolved with beta release.
